# spring.datasource.url=jdbc:postgresql://localhost:5432/login_db
# spring.datasource.username=postgres
# spring.datasource.password=12345678
spring.datasource.url=jdbc:postgresql://ep-misty-math-ay11z86f-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_rpdolIB7Dg2y
spring.jpa.hibernate.ddl-auto=update